CC=cc
ifeq ($(VIS),1)
	INC=-DVIS -I../../include/
endif
CFLAGS=-DROWS=2000 -DCOLS=2000 $(INC) -g 
LDFLAGS=
EXE=../../bin/heat_eq_mpi_${CRAY_CPU_TARGET}

mpi: heat_eq_mpi.o
	@mkdir -p ../../bin
	$(CC) $(CFLAGS) heat_eq_mpi.o -o $(EXE) $(LDFLAGS)

%.o: heat_eq_mpi.c
		$(CC) -c -o $@ $< $(CFLAGS)

clean:
		rm *.o $(EXE)
cleanall:
		rm *.o *.out *.vtk $(EXE)
